### ISSUE TITLE
sendTestEmailAction() limited to .txt.twig

### ISSUE THREAD

**Issue by Discutea** [azine/email-bundle#16]
Hi,

Is there a reason for this method to be limited to a text format?
What about HTML templates?

https://github.com/azine/email-bundle/blob/master/Controller/AzineEmailTemplateController.php#L328

**Comment by azine** [comment]
Hi David,

the bundle assumes that all emails are implemented with twig templates that follow the these conventions:
- Naming: temlpateId.txt.twig for the txt-part of the multipart email and templateId.html.twig for the html-part of the multipart email.
- Structure: the "templateId.txt.twig" includes the "templateId.html.twig. See [link](https://github.com/azine/email-bundle/blob/master/Resources/views/exampleEmailLayout.txt.twig#L38) for an example.
- As emails are always sent with a txt- and a html-part, the templates and also template variables are handled together and their shared id is the "templateId" => so the template-file name without the "txt.twig"

I chose this solution (including the html template in the txt template) because the FosUserBundle only accepts one argument for its "sendMessage").

If this is the best solution is open to discussion.

**Comment by Discutea** [comment]
Ok thanks,

I did not know this convention I adapted my view it is a very good that the EmailBundle forces us to respect the best practices of symfony 👍
